[package]
name = "classfile"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.10.0"
java_string = "0.1.3"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.17"

[dev-dependencies]
classfile_macros = { path = "./classfile_macros" }
